# Generated by Django 5.1.7 on 2025-05-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('recrutador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('Freelancer', 'Freelancer'), ('Estágio', 'Estágio'), ('Outro', 'Outro')], max_length=20)),
                ('vaga_ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('url_form', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutador.recrutador')),
            ],
        ),
    ]
