# Generated by Django 5.1.7 on 2025-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='tecnologias_requeridas',
        ),
        migrations.AddField(
            model_name='vaga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='vaga_ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('Freelancer', 'Freelancer'), ('Estágio', 'Estágio'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
