# Generated by Django 5.1.6 on 2025-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tecnologias', models.TextField()),
                ('experiencias', models.TextField()),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
    ]
