# Generated by Django 5.1.7 on 2025-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='experiencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desenvolvedor',
            name='tecnologias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
